apiVersion: v1
kind: PersistentVolume
metadata:
  name: mytomcat9-vol
spec:
  storageClassName: manual      
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/mytomcat9/

