apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mytomcat9
  name: mytomcat9
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: mytomcat9
  type: LoadBalancer
status:
  loadBalancer: {}
