apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mytomcat9
  name: mytomcat9
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mytomcat9
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mytomcat9
    spec:
      containers:
      - image: itechmog/mogtomcat9:v1
        name: mytomcat9
        resources: {}
status: {}
